# vim:ft=ansible:
---

# Install HAProxy and socat
- name: install haproxy and socat
  apt: pkg={{ item }} state=latest
  with_items:
  - haproxy
  - socat

# Enabling HAProxy
- name: enable haproxy
  lineinfile: dest=/etc/default/haproxy regexp="^ENABLED" line="ENABLED=1"
  notify: restart haproxy

# Deploy custom HAProxy config from templates
- name: deploy haproxy
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  notify: restart haproxy
