# vim:ft=ansible:
---

# Install nginx
- name: install nginx
  apt: name=nginx state=installed

# Update nginx conf
- name: write our nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: restart nginx

# Enable the default site config
- name: write our /etc/nginx/sites-available/default
  template: src=default-site.j2 dest=/etc/nginx/sites-available/default
  notify: restart nginx

# Replace the index.html
- name: update website content
  template: src=index.html.j2 dest=/usr/share/nginx/html/index.html


