# vim:ft=ansible:
---

# common
- hosts: all
  sudo: yes
  # gather_facts is true/yes by default
  gather_facts: no

  roles:
    - common

# web
- hosts: web
  sudo: yes
  serial: 1

  roles:
    - web

# lb
- hosts: lb
  sudo: yes

  roles:
    - lb
