# vim:ft=ansible:
---
# common role tasks
- hosts: all
  sudo: yes
  remote_user: vagrant
  gather_facts: no

  roles:
    - common

# web role tasks
- hosts: web
  sudo: yes
  serial: 1
  remote_user: vagrant

  roles:
    - web

# load balancer role tasks
- hosts: lb
  sudo: yes
  remote_user: vagrant

  roles:
    - lb
